// This file contains example code generated by Vivado for an IP with one 
// AXI-lite slave with 4 registers.

// It was modified to match the design in Section 6.3 by:
//    - adding new signls ps_control and pl_logic, which connect to
//      new ports in the maxval_with_bram_v1_0_S00_AXI module
//    - adding a BRAM slave interface
//    - adding an instance of the maxval module, which connects to the
//      BRAM slave interface and the ps_control and pl_logic signals

// This file is provided for educational purposes, to demonstrate how to modify
// the original Xilinx-generated design. The original code here is (C) Xilinx.

`timescale 1 ns / 1 ps

	module bram_int_max_val_v1_0 #
	(
		// Users to add parameters here

		// User parameters ends
		// Do not modify the parameters beyond this line


		// Parameters of Axi Slave Bus Interface S00_AXI
		parameter integer C_S00_AXI_DATA_WIDTH	= 32,
		parameter integer C_S00_AXI_ADDR_WIDTH	= 4
	)
	(

		// BRAM slave ports
		input wire [12:0]  bram_addr,
		input wire         bram_clk,
		input wire [31:0]  bram_wrdata,
		output wire [31:0] bram_rddata,
		input wire         bram_en,
		input wire         bram_rst,
		input wire [3:0]   bram_we, 

		// User ports ends
		// Do not modify the ports beyond this line


		// Ports of Axi Slave Bus Interface S00_AXI
		input wire  s00_axi_aclk,
		input wire  s00_axi_aresetn,
		input wire [C_S00_AXI_ADDR_WIDTH-1 : 0] s00_axi_awaddr,
		input wire [2 : 0] s00_axi_awprot,
		input wire  s00_axi_awvalid,
		output wire  s00_axi_awready,
		input wire [C_S00_AXI_DATA_WIDTH-1 : 0] s00_axi_wdata,
		input wire [(C_S00_AXI_DATA_WIDTH/8)-1 : 0] s00_axi_wstrb,
		input wire  s00_axi_wvalid,
		output wire  s00_axi_wready,
		output wire [1 : 0] s00_axi_bresp,
		output wire  s00_axi_bvalid,
		input wire  s00_axi_bready,
		input wire [C_S00_AXI_ADDR_WIDTH-1 : 0] s00_axi_araddr,
		input wire [2 : 0] s00_axi_arprot,
		input wire  s00_axi_arvalid,
		output wire  s00_axi_arready,
		output wire [C_S00_AXI_DATA_WIDTH-1 : 0] s00_axi_rdata,
		output wire [1 : 0] s00_axi_rresp,
		output wire  s00_axi_rvalid,
		input wire  s00_axi_rready
	);

	// Declare ps_control and pl_status signals
	wire [31:0] ps_control, pl_status;

	// Instantiation of Axi Bus Interface S00_AXI
	bram_int_max_val_v1_0_S00_AXI # ( 
		.C_S_AXI_DATA_WIDTH(C_S00_AXI_DATA_WIDTH),
		.C_S_AXI_ADDR_WIDTH(C_S00_AXI_ADDR_WIDTH)
	) bram_int_max_val_v1_0_S00_AXI_inst (
		.S_AXI_ACLK(s00_axi_aclk),
		.S_AXI_ARESETN(s00_axi_aresetn),
		.S_AXI_AWADDR(s00_axi_awaddr),
		.S_AXI_AWPROT(s00_axi_awprot),
		.S_AXI_AWVALID(s00_axi_awvalid),
		.S_AXI_AWREADY(s00_axi_awready),
		.S_AXI_WDATA(s00_axi_wdata),
		.S_AXI_WSTRB(s00_axi_wstrb),
		.S_AXI_WVALID(s00_axi_wvalid),
		.S_AXI_WREADY(s00_axi_wready),
		.S_AXI_BRESP(s00_axi_bresp),
		.S_AXI_BVALID(s00_axi_bvalid),
		.S_AXI_BREADY(s00_axi_bready),
		.S_AXI_ARADDR(s00_axi_araddr),
		.S_AXI_ARPROT(s00_axi_arprot),
		.S_AXI_ARVALID(s00_axi_arvalid),
		.S_AXI_ARREADY(s00_axi_arready),
		.S_AXI_RDATA(s00_axi_rdata),
		.S_AXI_RRESP(s00_axi_rresp),
		.S_AXI_RVALID(s00_axi_rvalid),
		.S_AXI_RREADY(s00_axi_rready),
		.pl_status(pl_status),
		.ps_control(ps_control)
	);

	// Add user logic here

	// Instantiate maxval module
	maxval_int mv(.clk(s00_axi_aclk),
			.reset(~s00_axi_aresetn),
			.ps_control(ps_control),
			.pl_status(pl_status),
			.ps_bram_clk(bram_clk),
			.ps_bram_addr(bram_addr),
			.ps_bram_rddata(bram_rddata),
			.ps_bram_wrdata(bram_wrdata),
			.ps_bram_we(bram_we),
			.ps_bram_en(bram_en));

	// User logic ends

	endmodule
